CREATE DATABASE MovimentosManuais;
GO

USE MovimentosManuais;
GO

CREATE TABLE PRODUTO (
COD_PRODUTO CHAR(4) NOT NULL,
DES_PRODUTO VARCHAR(30) NOT NULL,
STA_STATUS CHAR(1) NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
);
GO

CREATE TABLE PRODUTO_COSIF (
COD_PRODUTO CHAR(4) NOT NULL,
COD_COSIF VARCHAR(11) NOT NULL,
COD_CLASSIFICACAO CHAR(6) NOT NULL,
STA_STATUS CHAR(1) NOT NULL,

```
CONSTRAINT PK_PRODUTO_COSIF
    PRIMARY KEY (COD_PRODUTO, COD_COSIF),

CONSTRAINT FK_PRODUTO_COSIF_PRODUTO
    FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
```

);
GO

CREATE TABLE MOVIMENTO_MANUAL (
DAT_MES INT NOT NULL,
DAT_ANO INT NOT NULL,
NUM_LANCAMENTO INT NOT NULL,

```
COD_PRODUTO CHAR(4) NOT NULL,
COD_COSIF VARCHAR(11) NOT NULL,

VAL_VALOR NUMERIC(18,2) NOT NULL,
DES_DESCRICAO VARCHAR(50) NOT NULL,

DAT_MOVIMENTO SMALLDATETIME NOT NULL,
COD_USUARIO VARCHAR(15) NOT NULL,

CONSTRAINT PK_MOVIMENTO_MANUAL
    PRIMARY KEY
    (
        DAT_MES,
        DAT_ANO,
        NUM_LANCAMENTO
    ),

CONSTRAINT FK_MOVIMENTO_MANUAL_COSIF
    FOREIGN KEY
    (
        COD_PRODUTO,
        COD_COSIF
    )
    REFERENCES PRODUTO_COSIF
    (
        COD_PRODUTO,
        COD_COSIF
    )
```

);
GO

INSERT INTO PRODUTO VALUES
('0001','Produto A','A'),
('0002','Produto B','A');
GO

INSERT INTO PRODUTO_COSIF VALUES
('0001','12345678901','111111','A'),
('0001','12345678902','222222','A'),
('0002','12345678903','333333','A');
GO

CREATE OR ALTER PROCEDURE SP_CONSULTAR_MOVIMENTOS
AS
BEGIN

```
SELECT
    MM.DAT_MES,
    MM.DAT_ANO,
    MM.COD_PRODUTO,
    P.DES_PRODUTO,
    MM.NUM_LANCAMENTO,
    MM.DES_DESCRICAO,
    MM.VAL_VALOR,
    MM.DAT_MOVIMENTO
FROM MOVIMENTO_MANUAL MM
INNER JOIN PRODUTO P
    ON P.COD_PRODUTO = MM.COD_PRODUTO
ORDER BY
    MM.DAT_ANO,
    MM.DAT_MES,
    MM.NUM_LANCAMENTO;
```

END;
GO
